### ISSUE TITLE
EDF Exporter

### ISSUE THREAD

**Issue by teonbrooks** [OpenBCI/-DEPRECATED-OpenBCI_Processing#34]
We should have a standardized EEG export format. EDF is a standard format, but the only issue is that is stored in 16bit resolution versus the original 24bit.

**Comment by wjcroft** [comment]
As has been mentioned on the forum, EDFBrowser is a free utility that can convert between many formats, including our CSV, EDF, BDF, etc. BDF is the 24 bit version of EDF.

https://www.google.com/search?q=edf+bdf

**Comment by teonbrooks** [comment]
closing as this repo is now deprecated
